services:
  - type: web
    name: cloud-receipt-frontend
    env: node
    plan: free
    autoDeploy: true
    # Build: install deps, generate .env from Render env vars (if defined), then export web build
    buildCommand: |
      npm ci
      # Create .env for react-native-dotenv (optional). Add keys in Render > Environment.
      # Example: API_BASE_URL. Remove if not needed.
      if [ -n "$API_BASE_URL" ]; then echo "API_BASE_URL=$API_BASE_URL" > .env; fi
      npx expo --version
      # Export web build to ./dist (Expo SDK 49+). Adjust if your output dir differs.
      npx expo export --platform web
    startCommand: npx serve -s dist -l $PORT
    # Optional health check for static content
    healthCheckPath: /
    # Define build-time env vars here or via Render dashboard
    # envVars:
    #   - key: API_BASE_URL
    #     fromSecret: api-base-url
