name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc -v
            npx tsc --noEmit
          else
            echo "No TypeScript config, skipping type check"
          fi

      - name: Expo Web Export (optional)
        run: |
          if npm run | grep -q "web"; then
            npx expo --version
            # For Expo Router v3+/Expo SDK 50+, the command is `npx expo export --platform web`
            # Older versions used `expo export:web` or `expo export` without platform flag.
            # We'll try the modern command first, and fallback gracefully.
            if npx expo export --platform web; then
              echo "Expo web export completed"
            else
              echo "Modern export failed, trying legacy export:web"
              npx expo export:web || echo "Legacy export failed as well; skipping web export"
            fi
          else
            echo "No web script defined, skipping web export"
          fi
