name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Type check
        run: |
          if [ -f tsconfig.json ]; then
            npx tsc -v
            npx tsc --noEmit
          else
            echo "No TypeScript config, skipping type check"
          fi

      - name: Expo Web Export (optional)
        run: |
          if npm run | grep -q "web"; then
            npx expo export --platform web --force
          else
            echo "No web script defined, skipping web export"
          fi
